#pragma once

#include "MSF_Config.h"

#if !MSF_FORMAT_LOCAL_PLATFORM
// Config already set
#else

#if MSF_FORMAT_LOCAL_PLATFORM == MSF_FORMAT_PLATFORM_AUTO

#if defined(__ANDROID__)
#define MSF_FORMAT_SELECTED_PLATFORM MSF_FORMAT_PLATFORM_ANDROID
#elif defined(__APPLE__)
#define MSF_FORMAT_SELECTED_PLATFORM MSF_FORMAT_PLATFORM_APPLE
#elif defined(__linux__)
#define MSF_FORMAT_SELECTED_PLATFORM MSF_FORMAT_PLATFORM_LINUX
#elif defined(_MSC_VER)
#define MSF_FORMAT_SELECTED_PLATFORM MSF_FORMAT_PLATFORM_WINDOWS
#else
#define MSF_FORMAT_SELECTED_PLATFORM MSF_FORMAT_PLATFORM_LINUX
#endif // platform

#else
#define MSF_FORMAT_SELECTED_PLATFORM MSF_FORMAT_LOCAL_PLATFORM
#endif

#undef MSF_STRING_ALLOW_LEADING_ZERO
#undef MSF_STRING_PRECISION_IS_CHARACTERS
#undef MSF_STRING_NULL_ALL_OR_NOTHING
#undef MSF_WSTRING_WIDTH_IS_BYTES
#undef MSF_POINTER_FORCE_PRECISION
#undef MSF_POINTER_ADD_PREFIX
#undef MSF_POINTER_ADD_SIGN_OR_BLANK
#undef MSF_POINTER_PRINT_CAPS
#undef MSF_POINTER_PRINT_NIL
#undef MSF_FLOAT_EPSILON_AFFECTED_BY_PRECISION

#if MSF_FORMAT_SELECTED_PLATFORM == MSF_FORMAT_PLATFORM_ANDROID
#define MSF_STRING_ALLOW_LEADING_ZERO 1
#define MSF_STRING_PRECISION_IS_CHARACTERS 0
#define MSF_STRING_NULL_ALL_OR_NOTHING 1
#define MSF_WSTRING_WIDTH_IS_BYTES 0
#define MSF_POINTER_FORCE_PRECISION 0
#define MSF_POINTER_ADD_PREFIX 1
#define MSF_POINTER_ADD_SIGN_OR_BLANK 0
#define MSF_POINTER_PRINT_CAPS 0
#define MSF_POINTER_PRINT_NIL 1
#define MSF_FLOAT_EPSILON_AFFECTED_BY_PRECISION 0
#elif MSF_FORMAT_SELECTED_PLATFORM == MSF_FORMAT_PLATFORM_APPLE
#define MSF_STRING_ALLOW_LEADING_ZERO 1
#define MSF_STRING_PRECISION_IS_CHARACTERS 0
#define MSF_STRING_NULL_ALL_OR_NOTHING 1
#define MSF_WSTRING_WIDTH_IS_BYTES 0
#define MSF_POINTER_FORCE_PRECISION 0
#define MSF_POINTER_ADD_PREFIX 1
#define MSF_POINTER_ADD_SIGN_OR_BLANK 0
#define MSF_POINTER_PRINT_CAPS 0
#define MSF_POINTER_PRINT_NIL 1
#define MSF_FLOAT_EPSILON_AFFECTED_BY_PRECISION 0
#elif MSF_FORMAT_SELECTED_PLATFORM == MSF_FORMAT_PLATFORM_LINUX
#define MSF_STRING_ALLOW_LEADING_ZERO 0
#define MSF_STRING_PRECISION_IS_CHARACTERS 0
#define MSF_STRING_NULL_ALL_OR_NOTHING 1
#define MSF_WSTRING_WIDTH_IS_BYTES 0
#define MSF_POINTER_FORCE_PRECISION 0
#define MSF_POINTER_ADD_PREFIX 1
#define MSF_POINTER_ADD_SIGN_OR_BLANK 1
#define MSF_POINTER_PRINT_CAPS 0
#define MSF_POINTER_PRINT_NIL 1
#define MSF_FLOAT_EPSILON_AFFECTED_BY_PRECISION 0
#elif MSF_FORMAT_SELECTED_PLATFORM == MSF_FORMAT_PLATFORM_WINDOWS
#define MSF_STRING_ALLOW_LEADING_ZERO 1
#define MSF_STRING_PRECISION_IS_CHARACTERS 1
#define MSF_STRING_NULL_ALL_OR_NOTHING 0
#define MSF_WSTRING_WIDTH_IS_BYTES 1
#define MSF_POINTER_FORCE_PRECISION 1
#define MSF_POINTER_ADD_PREFIX 0
#define MSF_POINTER_ADD_SIGN_OR_BLANK 0
#define MSF_POINTER_PRINT_CAPS 1
#define MSF_POINTER_PRINT_NIL 0
#define MSF_FLOAT_EPSILON_AFFECTED_BY_PRECISION 1
#else
#error "MSF_FORMAT_SELECTED_PLATFORM got set to an unknown platform value"
#endif

#endif // MSF_FORMAT_LOCAL_PLATFORM