#pragma once

#include "MSF_Config.h"

#if MSF_FORMAT_LOCAL_PLATFORM

#undef MSF_STRING_ALLOW_LEADING_ZERO
#undef MSF_STRING_PRECISION_IS_CHARACTERS
#undef MSF_STRING_NULL_ALL_OR_NOTHING
#undef MSF_WSTRING_WIDTH_IS_BYTES
#undef MSF_POINTER_FORCE_PRECISION
#undef MSF_POINTER_ADD_PREFIX
#undef MSF_POINTER_ADD_SIGN_OR_BLANK
#undef MSF_POINTER_PRINT_CAPS
#undef MSF_POINTER_PRINT_NIL

#if defined(__ANDROID__)
#define MSF_STRING_ALLOW_LEADING_ZERO 1
#define MSF_STRING_PRECISION_IS_CHARACTERS 0
#define MSF_STRING_NULL_ALL_OR_NOTHING 1
#define MSF_WSTRING_WIDTH_IS_BYTES 0
#define MSF_POINTER_FORCE_PRECISION 0
#define MSF_POINTER_ADD_PREFIX 1
#define MSF_POINTER_ADD_SIGN_OR_BLANK 0
#define MSF_POINTER_PRINT_CAPS 0
#define MSF_POINTER_PRINT_NIL 1
#elif defined(__APPLE__)
#define MSF_STRING_ALLOW_LEADING_ZERO 1
#define MSF_STRING_PRECISION_IS_CHARACTERS 0
#define MSF_STRING_NULL_ALL_OR_NOTHING 1
#define MSF_WSTRING_WIDTH_IS_BYTES 0
#define MSF_POINTER_FORCE_PRECISION 0
#define MSF_POINTER_ADD_PREFIX 1
#define MSF_POINTER_ADD_SIGN_OR_BLANK 0
#define MSF_POINTER_PRINT_CAPS 0
#define MSF_POINTER_PRINT_NIL 1
#elif defined(__linux__)
#define MSF_STRING_ALLOW_LEADING_ZERO 0
#define MSF_STRING_PRECISION_IS_CHARACTERS 0
#define MSF_STRING_NULL_ALL_OR_NOTHING 1
#define MSF_WSTRING_WIDTH_IS_BYTES 0
#define MSF_POINTER_FORCE_PRECISION 0
#define MSF_POINTER_ADD_PREFIX 1
#define MSF_POINTER_ADD_SIGN_OR_BLANK 1
#define MSF_POINTER_PRINT_CAPS 0
#define MSF_POINTER_PRINT_NIL 1
#elif defined(_MSC_VER)
#define MSF_STRING_ALLOW_LEADING_ZERO 1
#define MSF_STRING_PRECISION_IS_CHARACTERS 1
#define MSF_STRING_NULL_ALL_OR_NOTHING 0
#define MSF_WSTRING_WIDTH_IS_BYTES 1
#define MSF_POINTER_FORCE_PRECISION 1
#define MSF_POINTER_ADD_PREFIX 0
#define MSF_POINTER_ADD_SIGN_OR_BLANK 0
#define MSF_POINTER_PRINT_CAPS 1
#define MSF_POINTER_PRINT_NIL 0
#else
#error "Unsupported platform"
#endif

#endif // MSF_FORMAT_LOCAL_PLATFORM